// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT
import {session} from '../models';

export function CloseSession(arg1:string):Promise<void>;

export function CreateSession(arg1:string,arg2:session.ConnectionConfig):Promise<session.SessionInfo>;

export function ListSessions():Promise<Array<session.SessionInfo>>;

export function LoadConnections():Promise<Array<session.ConnectionConfig>>;

export function SaveConnections(arg1:Array<session.ConnectionConfig>):Promise<void>;

export function SessionWrite(arg1:string,arg2:string):Promise<void>;
