// @ts-check
// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

export function CloseSession(arg1) {
  return window['go']['main']['App']['CloseSession'](arg1);
}

export function CreateSession(arg1, arg2) {
  return window['go']['main']['App']['CreateSession'](arg1, arg2);
}

export function ListSessions() {
  return window['go']['main']['App']['ListSessions']();
}

export function LoadConnections() {
  return window['go']['main']['App']['LoadConnections']();
}

export function SaveConnections(arg1) {
  return window['go']['main']['App']['SaveConnections'](arg1);
}

export function SessionWrite(arg1, arg2) {
  return window['go']['main']['App']['SessionWrite'](arg1, arg2);
}
