// @ts-check
// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

export function ChatCompletion(arg1, arg2, arg3, arg4, arg5) {
  return window['go']['main']['App']['ChatCompletion'](arg1, arg2, arg3, arg4, arg5);
}

export function CloseSession(arg1) {
  return window['go']['main']['App']['CloseSession'](arg1);
}

export function CreateSession(arg1, arg2) {
  return window['go']['main']['App']['CreateSession'](arg1, arg2);
}

export function GetDesktopPath() {
  return window['go']['main']['App']['GetDesktopPath']();
}

export function GetPlatform() {
  return window['go']['main']['App']['GetPlatform']();
}

export function ListSessions() {
  return window['go']['main']['App']['ListSessions']();
}

export function LoadAIConfig() {
  return window['go']['main']['App']['LoadAIConfig']();
}

export function LoadConnections() {
  return window['go']['main']['App']['LoadConnections']();
}

export function LoadSettings() {
  return window['go']['main']['App']['LoadSettings']();
}

export function OnConnectionsChanged(arg1) {
  return window['go']['main']['App']['OnConnectionsChanged'](arg1);
}

export function OpenDirectoryDialog() {
  return window['go']['main']['App']['OpenDirectoryDialog']();
}

export function OpenFileDialog() {
  return window['go']['main']['App']['OpenFileDialog']();
}

export function OpenMultipleFilesDialog() {
  return window['go']['main']['App']['OpenMultipleFilesDialog']();
}

export function RDPHide(arg1) {
  return window['go']['main']['App']['RDPHide'](arg1);
}

export function RDPSetFocus(arg1, arg2) {
  return window['go']['main']['App']['RDPSetFocus'](arg1, arg2);
}

export function RDPSetPosition(arg1, arg2, arg3, arg4, arg5) {
  return window['go']['main']['App']['RDPSetPosition'](arg1, arg2, arg3, arg4, arg5);
}

export function RDPShow(arg1) {
  return window['go']['main']['App']['RDPShow'](arg1);
}

export function RemoveTempFile(arg1) {
  return window['go']['main']['App']['RemoveTempFile'](arg1);
}

export function SaveAIConfig(arg1) {
  return window['go']['main']['App']['SaveAIConfig'](arg1);
}

export function SaveConnections(arg1) {
  return window['go']['main']['App']['SaveConnections'](arg1);
}

export function SaveFileDialog(arg1) {
  return window['go']['main']['App']['SaveFileDialog'](arg1);
}

export function SaveSettings(arg1) {
  return window['go']['main']['App']['SaveSettings'](arg1);
}

export function SessionResize(arg1, arg2, arg3) {
  return window['go']['main']['App']['SessionResize'](arg1, arg2, arg3);
}

export function SessionWrite(arg1, arg2) {
  return window['go']['main']['App']['SessionWrite'](arg1, arg2);
}

export function SftpCancelTransfer(arg1, arg2) {
  return window['go']['main']['App']['SftpCancelTransfer'](arg1, arg2);
}

export function SftpChangeLocalDir(arg1, arg2) {
  return window['go']['main']['App']['SftpChangeLocalDir'](arg1, arg2);
}

export function SftpChangeRemoteDir(arg1, arg2) {
  return window['go']['main']['App']['SftpChangeRemoteDir'](arg1, arg2);
}

export function SftpChmod(arg1, arg2, arg3) {
  return window['go']['main']['App']['SftpChmod'](arg1, arg2, arg3);
}

export function SftpGet(arg1, arg2, arg3, arg4) {
  return window['go']['main']['App']['SftpGet'](arg1, arg2, arg3, arg4);
}

export function SftpListLocal(arg1, arg2) {
  return window['go']['main']['App']['SftpListLocal'](arg1, arg2);
}

export function SftpListLocalDrives(arg1) {
  return window['go']['main']['App']['SftpListLocalDrives'](arg1);
}

export function SftpListRemote(arg1, arg2) {
  return window['go']['main']['App']['SftpListRemote'](arg1, arg2);
}

export function SftpLocalMkdir(arg1, arg2) {
  return window['go']['main']['App']['SftpLocalMkdir'](arg1, arg2);
}

export function SftpLocalRemove(arg1, arg2, arg3) {
  return window['go']['main']['App']['SftpLocalRemove'](arg1, arg2, arg3);
}

export function SftpLocalRename(arg1, arg2, arg3) {
  return window['go']['main']['App']['SftpLocalRename'](arg1, arg2, arg3);
}

export function SftpMakeDir(arg1, arg2) {
  return window['go']['main']['App']['SftpMakeDir'](arg1, arg2);
}

export function SftpPauseTransfer(arg1, arg2) {
  return window['go']['main']['App']['SftpPauseTransfer'](arg1, arg2);
}

export function SftpPut(arg1, arg2, arg3, arg4) {
  return window['go']['main']['App']['SftpPut'](arg1, arg2, arg3, arg4);
}

export function SftpPutContent(arg1, arg2, arg3) {
  return window['go']['main']['App']['SftpPutContent'](arg1, arg2, arg3);
}

export function SftpRemove(arg1, arg2, arg3) {
  return window['go']['main']['App']['SftpRemove'](arg1, arg2, arg3);
}

export function SftpRename(arg1, arg2, arg3) {
  return window['go']['main']['App']['SftpRename'](arg1, arg2, arg3);
}

export function SftpResumeTransfer(arg1, arg2) {
  return window['go']['main']['App']['SftpResumeTransfer'](arg1, arg2);
}

export function WriteTempFile(arg1, arg2) {
  return window['go']['main']['App']['WriteTempFile'](arg1, arg2);
}
