// @ts-check
// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

export function ChatCompletion(arg1, arg2, arg3, arg4, arg5) {
  return window['go']['main']['App']['ChatCompletion'](arg1, arg2, arg3, arg4, arg5);
}

export function CloseSession(arg1) {
  return window['go']['main']['App']['CloseSession'](arg1);
}

export function CreateSession(arg1, arg2) {
  return window['go']['main']['App']['CreateSession'](arg1, arg2);
}

export function ListSessions() {
  return window['go']['main']['App']['ListSessions']();
}

export function LoadAIConfig() {
  return window['go']['main']['App']['LoadAIConfig']();
}

export function LoadConnections() {
  return window['go']['main']['App']['LoadConnections']();
}

export function LoadSettings() {
  return window['go']['main']['App']['LoadSettings']();
}

export function OnConnectionsChanged(arg1) {
  return window['go']['main']['App']['OnConnectionsChanged'](arg1);
}

export function SaveAIConfig(arg1) {
  return window['go']['main']['App']['SaveAIConfig'](arg1);
}

export function SaveConnections(arg1) {
  return window['go']['main']['App']['SaveConnections'](arg1);
}

export function SaveSettings(arg1) {
  return window['go']['main']['App']['SaveSettings'](arg1);
}

export function SessionResize(arg1, arg2, arg3) {
  return window['go']['main']['App']['SessionResize'](arg1, arg2, arg3);
}

export function SessionWrite(arg1, arg2) {
  return window['go']['main']['App']['SessionWrite'](arg1, arg2);
}

export function OpenFileDialog() {
  return window['go']['main']['App']['OpenFileDialog']();
}

export function SaveFileDialog(arg1) {
  return window['go']['main']['App']['SaveFileDialog'](arg1);
}
